--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/mnt/hdd/ironman/wallpapers/wallhaven-ym929g.png"

-- Special
background="#0d0d0c"
foreground="#e5e3df"
cursor="#e5e3df"

-- Colors
color0="#0d0d0c"
color1="#F4AD40"
color2="#FFC442"
color3="#F6CC71"
color4="#7D7E81"
color5="#908F8F"
color6="#E7D1A5"
color7="#e5e3df"
color8="#a09e9c"
color9="#F4AD40"
color10="#FFC442"
color11="#F6CC71"
color12="#7D7E81"
color13="#908F8F"
color14="#E7D1A5"
color15="#e5e3df"
