--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ironman/wallpapers/wallhaven-771586.jpg"

-- Special
background="#101311"
foreground="#e5dfce"
cursor="#e5dfce"

-- Colors
color0="#101311"
color1="#4E8D5E"
color2="#98A73F"
color3="#9B9863"
color4="#57708F"
color5="#59A888"
color6="#AFB695"
color7="#e5dfce"
color8="#a09c90"
color9="#4E8D5E"
color10="#98A73F"
color11="#9B9863"
color12="#57708F"
color13="#59A888"
color14="#AFB695"
color15="#e5dfce"
