# Shell variables
# Generated by 'wal'
wallpaper='/mnt/hdd/ironman/wallpapers/wallhaven-ym929g.png'

# Special
background='#0d0d0c'
foreground='#e5e3df'
cursor='#e5e3df'

# Colors
color0='#0d0d0c'
color1='#F4AD40'
color2='#FFC442'
color3='#F6CC71'
color4='#7D7E81'
color5='#908F8F'
color6='#E7D1A5'
color7='#e5e3df'
color8='#a09e9c'
color9='#F4AD40'
color10='#FFC442'
color11='#F6CC71'
color12='#7D7E81'
color13='#908F8F'
color14='#E7D1A5'
color15='#e5e3df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
