--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/mnt/hdd/ironman/wallpapers/wallhaven-728478.jpg"

-- Special
background="#060A0F"
foreground="#c7bec2"
cursor="#c7bec2"

-- Colors
color0="#060A0F"
color1="#CF6447"
color2="#E48D5A"
color3="#36768A"
color4="#987A86"
color5="#0F92A1"
color6="#63929E"
color7="#c7bec2"
color8="#8b8587"
color9="#CF6447"
color10="#E48D5A"
color11="#36768A"
color12="#987A86"
color13="#0F92A1"
color14="#63929E"
color15="#c7bec2"
