# Shell variables
# Generated by 'wal'
wallpaper='/home/ironman/wallpapers/wallhaven-771586.jpg'

# Special
background='#101311'
foreground='#e5dfce'
cursor='#e5dfce'

# Colors
color0='#101311'
color1='#4E8D5E'
color2='#98A73F'
color3='#9B9863'
color4='#57708F'
color5='#59A888'
color6='#AFB695'
color7='#e5dfce'
color8='#a09c90'
color9='#4E8D5E'
color10='#98A73F'
color11='#9B9863'
color12='#57708F'
color13='#59A888'
color14='#AFB695'
color15='#e5dfce'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
