# Shell variables
# Generated by 'wal'
wallpaper='/mnt/hdd/ironman/wallpapers/wallhaven-728478.jpg'

# Special
background='#060A0F'
foreground='#c7bec2'
cursor='#c7bec2'

# Colors
color0='#060A0F'
color1='#CF6447'
color2='#E48D5A'
color3='#36768A'
color4='#987A86'
color5='#0F92A1'
color6='#63929E'
color7='#c7bec2'
color8='#8b8587'
color9='#CF6447'
color10='#E48D5A'
color11='#36768A'
color12='#987A86'
color13='#0F92A1'
color14='#63929E'
color15='#c7bec2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
