#! /bin/sh

sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width		3
bspc config window_gap			0
bspc config bottom_padding      27

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set the border colors.
#bspc config normal_border_color "$color1"
bspc config normal_border_color "#202328"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color7"
#bspc config focused_border_color "#FFFFFF"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < -1.9.4
#bspc config presel_border_color "$color1"


# desktop rules
#bspc rule -a qutebrowser desktop='^1'
bspc rule -a Chromium desktop='^1'
bspc rule -a "java-lang-Thread"  desktop='^2' state=floating
bspc rule -a jetbrains-studio desktop='^2'
bspc rule -a jetbrains-webstorm desktop='^2'
bspc rule -a  "jetbrains-pycharm-ce" desktop='^2'
bspc rule -a Thunar state=floating rectangle=1000x600+500+300
bspc rule -a Genymotion state=floating
bspc rule -a "Android Emulator" state=floating
bspc rule -a "Genymotion Player" desktop='^3' state=floating
bspc rule -a Unity desktop='^4' state=floating
bspc rule -a Pavucontrol state=floating rectangle=1000x600+500+300
bspc rule -a Leafpad state=floating
bspc rule -a Sxiv state=floating rectangle=1000x1000+0+0
#bspc rule -a Zathura state=floating rectangle=1000x1000+0+0
bspc rule -a Zathura state=tiled

# transparency
# picom &	

# change keycode
xmodmap ~/.Xmodmap &

# set wallpaper
wal -i $(cat ~/.cache/wal/wal) -o ~/scripts/setWal.sh &

# status bar
~/.config/polybar/launch.sh

# keyboard mouse speed
xset r rate 500 40

# set curser  style to pointer
exec xsetroot -cursor_name left_ptr &                                                                       
#exec mpd &

# kde Connect
/usr/lib/kdeconnectd &

# track all my activies in this machine
#rescuetime &

# notification
dunst &

# source the colors.
#~/.cache/wal/colors.sh

# start local server
#~/scripts/startServer.sh &
# start syning file with mobile
syncthing &

