#!/usr/bin/env python

import datetime
import sys

help_text = """Obsidian tool
-t add task
-T add #todo task
-l add list
-L add line
"""


#  DD-MM-Y
def get_today_file_location():
    # vault location
    vault_location = "/home/ironman/obsidians/tmp/Brain/dailyNotes/"
    return f"{vault_location}{datetime.datetime.now().strftime('%d-%m-%Y')}.md"


def add_line_to_file(text):
    with open(get_today_file_location(), "a") as file:
        file.write(text)


if __name__ == '__main__':
    if len(sys.argv) <= 1:
        print(help_text)
    else:
        option = sys.argv[1]
        if option == "-t":
            add_line_to_file(f"\n- [ ] {''.join(sys.argv[2:])}")
        elif option == "-T":
            add_line_to_file(f"\n- [ ] {''.join(sys.argv[2:])} #todo")
        elif option == "-l":
            add_line_to_file(f"\n- {''.join(sys.argv[2:])}")
        elif option == "-L":
            add_line_to_file(f"\n{''.join(sys.argv[2:])}")
